### ISSUE TITLE
Make sure comparison with empty spectra yields N/A

### ISSUE THREAD

**Issue by sneumann** [rformassspectrometry/Spectra#130] opened 2020-09-10 07:16 UTC
Hi, 
@michaelwitting found that comparison with an empty spectrum hangs. Instead it should return N/A.
Stay tuned for details and test case. 
Yours, 
Steffen

**Comment by jorainer** [comment] 2020-09-11 14:37
This is strange. I can not reproduce:

```r
sps2 <- Spectra()
res <- compareSpectra(sps2)
res
<0 x 0 matrix>
```

and if one of the two `Spectra` is not empty (in this case having length 20):

```r
res <- compareSpectra(sps, sps2)
res     
 [1,]
 [2,]
 [3,]
 [4,]
 [5,]
 [6,]
 [7,]
 [8,]
 [9,]
[10,]
[11,]
[12,]
[13,]
[14,]
[15,]
[16,]
[17,]
[18,]
[19,]
[20,]
```

**Comment by michaelwitting** [comment] 2020-09-11 16:02
I created the spectra via a `DataFrame`, because I want to fill some gaps in a `Spectra` object. I set mz and intensity to NA instead of having it empty. That caused the problem. If I use an empty list its fine!

**Comment by jorainer** [comment] 2020-09-14 05:43
Thanks for the clarification. A simple example would help too. In general, `NA_real_` intensity values should be supported but `NA_real_` m/z values not.

**Comment by jorainer** [comment] 2020-10-21 06:03
Closing this issue now - feel free to re-open if needed.

**Closed by jorainer** 2020-10-21 06:03 UTC
